# Generated by Django 4.0.2 on 2022-02-25 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('currency', '0001_initial'),
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('negotiable', models.BooleanField(default=False)),
                ('bedrooms', models.IntegerField(blank=True)),
                ('square_size', models.IntegerField(blank=True)),
                ('lot_size', models.FloatField(blank=True)),
                ('garage', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('boys_quarters', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('furnished_state', models.CharField(blank=True, choices=[('FF', 'Fully Furnished'), ('SF', 'Semi Furnished')], max_length=20)),
                ('main_image', models.ImageField(upload_to='main_image_property/&Y/&m/&d/')),
                ('main_image_1', models.ImageField(blank=True, upload_to='main_image_1_property/&Y/&m/&d/')),
                ('main_image6', models.ImageField(blank=True, upload_to='main_image_property/&Y/&m/&d/')),
                ('main_image5', models.ImageField(blank=True, upload_to='main_image_property/&Y/&m/&d/')),
                ('main_image4', models.ImageField(blank=True, upload_to='main_image_property/&Y/&m/&d/')),
                ('main_image3', models.ImageField(blank=True, upload_to='main_image_property/&Y/&m/&d/')),
                ('image2', models.ImageField(blank=True, upload_to='main_image_property/&Y/&m/&d/')),
                ('property_video', models.FileField(blank=True, null=True, upload_to='videos_uploaded_properties', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('floor_plan', models.ImageField(blank=True, upload_to='floor_plan')),
                ('first_floor', models.ImageField(blank=True, upload_to='first_floor')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='currency.currencies')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.realtor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='region.region')),
            ],
        ),
    ]
