# Generated by Django 4.0.2 on 2022-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='furnished_state',
            field=models.CharField(blank=True, choices=[('SF', 'Semi Furnished'), ('FF', 'Fully Furnished')], max_length=20),
        ),
    ]
