# Generated by Django 3.2.11 on 2022-02-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
        ('listings', '0003_auto_20220225_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='newly_built',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='realtor.realtor'),
        ),
    ]
