# Generated by Django 4.0.2 on 2022-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('name_of_agency', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='Realtor/&Y/&m/&d/')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
